### ISSUE TITLE
Fork to contribute or fork for myself? 

### ISSUE THREAD

**Issue by ValeriePineauNoel** [JeremieGince/DefiProgFest2024-Admin#1]
![Screenshot 2023-11-13 at 4 25 32 PM](https://github.com/JeremieGince/DefiProgFest2024-Admin/assets/40174887/912c23a5-9a5b-44b0-ae1e-d97424e8b6ec)

C'est pas clair dans le readme lequel on doit sélectionner quand on fork le défiprog (et je ne sais pas si ça change dequoi non plus honnêtement, je fork pas mal jamais dans ma vie).

**Comment by rem657** [comment]
Ok je comprends je vais ajouter des détails dans le readme
